services:
  gringottsbankapi:
    image: ${DOCKER_REGISTRY-}gringottsbankapi
    build:
      context: .
      dockerfile: GringottsBankAPI/Dockerfile
  gringottsbankui:
    build:
      context: ./GringottsBankUI
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000"
    volumes:
      - ./GringottsBankUI:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - gringottsbankapi
